### ISSUE TITLE
Add bash completion for fpm response file

### ISSUE THREAD

**Issue by gha3mi** [ShinobuAmasaki/fpm-completions#4]
Hi,

Thank you for the project.

I have added `bash` completion for `fpm.rsp` files here: https://github.com/gha3mi/fpm-completions

May I send a pull request?

Best,
Ali

[Edited]: I am not a `zsh` user, so I am unable to provide the same for `zsh`. Perhaps, this could be easily added for the zsh script too.

**Comment by ShinobuAmasaki** [comment]
Hi.

Thank you for using this package.

It would be helpful if you could send a pull request, I can easily check how it works, so please feel free to send me pull-request.

By the way, I have never used the functionality of the file `fpm.rsp`, so if you have a simple reference on how to use it,
I think I can do a review promptly.

Regarding the same completions on zsh, I will intend to check the contents before reflecting them in the zsh's code.
